//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.0-rc.5

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "device_token")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(unique)]
    pub token: String,
    pub platform: String,
    pub device_id: Option<String>,
    pub user_id: Option<i32>,
    pub is_active: bool,
    pub last_used_at: Option<DateTime>,
    pub created_at: DateTime,
    pub updated_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::event_subscription::Entity")]
    EventSubscription,
}

impl Related<super::event_subscription::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::EventSubscription.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
