//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "events")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub name: String,
    pub description: String,
    #[sea_orm(column_type = "custom(\"daterange\")", nullable)]
    pub event_date_range: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::vendors::Entity")]
    Vendors,
}

impl Related<super::vendors::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Vendors.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
