//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.0-rc.5

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "event_subscription")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub device_token_id: i32,
    pub event_id: i32,
    pub is_active: bool,
    pub subscribed_at: DateTime,
    pub unsubscribed_at: Option<DateTime>,
    pub created_at: DateTime,
    pub updated_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::device_token::Entity",
        from = "Column::DeviceTokenId",
        to = "super::device_token::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    DeviceToken,
    #[sea_orm(
        belongs_to = "super::event::Entity",
        from = "Column::EventId",
        to = "super::event::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Event,
}

impl Related<super::device_token::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DeviceToken.def()
    }
}

impl Related<super::event::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Event.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
