//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.0-rc.5

pub mod prelude;

pub mod account;
pub mod device_token;
pub mod event;
pub mod notification;
pub mod notification_delivery;
pub mod schedule_image;
pub mod schedule_item;
pub mod vendor;
pub mod vendor_image;
pub mod vendor_inventory_item;
