//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};
use crate::sea_orm::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "schedule_images")]
#[serde(rename_all = "camelCase")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub schedule_item_id: i32,
    pub url: String,
    pub text: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::schedule_items::Entity",
        from = "Column::ScheduleItemId",
        to = "super::schedule_items::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    ScheduleItems,
}

impl Related<super::schedule_items::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ScheduleItems.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}

impl Entity {
    pub fn new_active_model(schedule_item_id: i32, key: &str, text: &str) -> ActiveModel {
        ActiveModel {
            schedule_item_id: Set(schedule_item_id),
            url: Set(key.to_string()),
            text: Set(text.to_string()),
            ..Default::default()
        }
    }

    pub async fn create_schedule_image(
        db: &DatabaseConnection,
        schedule_item_id: i32,
        key: &str,
        text: &str,
    ) -> Result<(), DbErr> {
        let schedule_image = Self::new_active_model(schedule_item_id, key, text);
        Self::insert(schedule_image).exec(db).await?;
        Ok(())
    }
}
