//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

use sea_orm::{entity::prelude::*, prelude::async_trait::async_trait, Set};
use serde::{Deserialize, Serialize};
use sqlx::types::chrono::Utc;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "schedule_items")]
#[serde(rename_all = "camelCase")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub title: String,
    pub description: String,
    pub start_date: DateTime,
    pub end_date: DateTime,
    pub created_at: DateTime,
    pub updated_at: DateTime,
    pub event_id: i32,
    pub thumbnail: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::schedule_images::Entity")]
    ScheduleImages,
    #[sea_orm(
        belongs_to = "super::events::Entity",
        from = "Column::EventId",
        to = "super::events::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Events,
}

impl Related<super::schedule_images::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ScheduleImages.def()
    }
}

impl Related<super::events::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Events.def()
    }
}

#[async_trait]
impl ActiveModelBehavior for ActiveModel {
    async fn before_save<C>(mut self, _: &C, insert: bool) -> Result<Self, DbErr> 
        where C: ConnectionTrait
    {
        if insert {
            self.created_at = Set(Utc::now().naive_utc());
        }
        self.updated_at = Set(Utc::now().naive_utc());
        Ok(self)
    }
}
