//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.0-rc.5

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "vendor_inventory_items")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub name: String,
    pub category: String,
    pub vendor_id: i32,
    pub event_id: i32,
    pub thumbnail: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::vendors::Entity",
        from = "Column::VendorId",
        to = "super::vendors::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Vendors,
}

impl Related<super::vendors::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Vendors.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
