//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.0-rc.5

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};
use strum::Display;

#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize, Display)]
#[sea_orm(rs_type = "String", db_type = "Text")]
#[strum(serialize_all = "snake_case")]
pub enum InventoryCategory {
    #[sea_orm(string_value = "drink")]
    Drink,
    #[sea_orm(string_value = "food")]
    Food,
    #[sea_orm(string_value = "merchandise")]
    Merchandise,
}

impl TryFrom<&str> for InventoryCategory {
    type Error = String;

    fn try_from(s: &str) -> Result<Self, Self::Error> {
        match s {
            "drink" => Ok(InventoryCategory::Drink),
            "food" => Ok(InventoryCategory::Food),
            "merchandise" => Ok(InventoryCategory::Merchandise),
            _ => Err(format!(
                "Invalid category '{}'. Valid options: beer, cider, wine, spirits, non_alcoholic, food, merchandise",
                s
            )),
        }
    }
}

impl TryFrom<String> for InventoryCategory {
    type Error = String;

    fn try_from(s: String) -> Result<Self, Self::Error> {
        s.as_str().try_into()
    }
}

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "vendor_inventory_item")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub name: String,
    pub category: InventoryCategory,
    pub subcategory: Option<String>,
    pub vendor_id: i32,
    pub event_id: i32,
    pub thumbnail: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::vendor::Entity",
        from = "Column::VendorId",
        to = "super::vendor::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Vendors,
}

impl Related<super::vendor::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Vendors.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
