//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.0-rc.5

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "vendor")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub name: String,
    pub email: String,
    pub phone: String,
    pub created_at: DateTime,
    pub updated_at: DateTime,
    pub event_id: i32,
    #[sea_orm(column_type = "Double", nullable)]
    pub latitude: Option<f64>,
    #[sea_orm(column_type = "Double", nullable)]
    pub longitude: Option<f64>,
    pub category: String,
    pub thumbnail: Option<String>,
    pub operating_out_of: String,
    pub description: String,
    pub vendor_type: Option<String>,
    pub booth: Option<String>,
    pub is_featured: bool,
    pub tags: Vec<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::event::Entity",
        from = "Column::EventId",
        to = "super::event::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Event,
    #[sea_orm(has_many = "super::vendor_image::Entity")]
    VendorImage,
    #[sea_orm(has_many = "super::vendor_inventory_item::Entity")]
    VendorInventoryItem,
}

impl Related<super::event::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Event.def()
    }
}

impl Related<super::vendor_image::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::VendorImage.def()
    }
}

impl Related<super::vendor_inventory_item::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::VendorInventoryItem.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
