//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};
use crate::{events, sea_orm::*, vendors};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "vendor_images")]
#[serde(rename_all = "camelCase")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub vendor_id: i32,
    pub url: String,
    pub text: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::vendors::Entity",
        from = "Column::VendorId",
        to = "super::vendors::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Vendors,
}

impl Related<super::vendors::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Vendors.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}

impl Entity {
    pub fn new_active_model(vendor_id: i32, key: &str, text: &str) -> ActiveModel {
        ActiveModel {
            vendor_id: Set(vendor_id),
            url: Set(key.to_string()),
            text: Set(text.to_string()),
            ..Default::default()
        }
    }

    pub async fn create_vendor_image(
        db: &DatabaseConnection,
        event_id: i32,
        vendor_id: i32,
        key: &str,
        text: &str,
    ) -> Result<(), DbErr> {
        events::Entity::find_by_id(event_id)
            .one(db)
            .await?
            .ok_or(DbErr::RecordNotFound(String::from("Event not found")))?
            .find_related(vendors::Entity)
            .filter(vendors::Column::Id.eq(vendor_id))
            .one(db)
            .await?
            .ok_or(DbErr::RecordNotFound(String::from("Vendor not found")))?;

        let new_image = Self::new_active_model(vendor_id, key, text);

        Self::insert(new_image).exec(db).await?;
        Ok(())
    }
}
